version: "3.6"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "500MB"


  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
      - POSTGRES_LOG_STATEMENT=none
      - POSTGRES_MAX_CONNECTIONS=200
      - POSTGRES_SHARED_BUFFERS=180MB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    command: ["postgres",
              "-c", "max_connections=500",
              "-c", "log_statement=none",
              "-c", "random_page_cost=1.1",
              "-c", "fsync=off",
              "-c", "full_page_writes=off",
              "-c", "work_mem=50MB",
              ]
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "180MB"

  api01: &api
    build:
      context: .
    hostname: api01
    environment:
      - DATABASE_URL=postgres://rinha:rinha@db:5432/rinha?sslmode=disable
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
