version: "3.5"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
      - POSTGRES_LOG_STATEMENT=none
      - POSTGRES_MAX_CONNECTIONS=200
      - POSTGRES_SHARED_BUFFERS=180MB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    command: ["postgres", "-c", "max_connections=200","-c", "log_statement=none"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "340MB"
  api01: &api
    build:
      context: .
    hostname: api01
    environment:
      - DATABASE_URL=postgres://rinha:rinha@db:5432/rinha
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
